# Generated by Django 4.1.1 on 2022-12-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='setSelectedFile',
            field=models.ImageField(default=2, upload_to='image', verbose_name='file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, verbose_name='username'),
        ),
    ]
